name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t weather-project .
      
      - name: Save Docker image
        run: docker save -o weather-project.tar weather-project

      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: faebebee@gmail.com
          heroku_api_key: ef74d377-97d2-4c94-9e07-f64a43b4f021
          heroku_app_name: murmuring-lake-77657
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
          docker_image_path: ./weather-project.tar
